### ISSUE TITLE
Fix matlab description files

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy-description#20]
Fix the DH parameters on the matlab description files.

**Comment by mikearagao** [comment]
@plinioMoreno please tag @ruipimentelfigueiredo on closing this issue so that he can work on issue https://github.com/vislab-tecnico-lisboa/vizzy-description/issues/5.

**Comment by plinioMoreno** [comment]
Done!! @ruipimentelfigueiredo go ahead and work on issue 
https://github.com/vislab-tecnico-lisboa/vizzy-description/issues/5
