### ISSUE TITLE
Align the URDF's Denavit–Hartenberg parameters with the real robot

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy-description#5]
@ruipimentelfigueiredo I'll do this asap! The real robot is now stable so the next version should be final :+1:

**Comment by mikearagao** [comment]
@plinioMoreno we were looking at the translations and it looks like the real robot has a small one on the head that is not on the matlab description files. Maybe there is some explanation for the absence of that translation and I don't know it. If not, we need to update the matlab files.

**Comment by mikearagao** [comment]
@plinioMoreno we were looking at the translations and it looks like the real robot has a small one on the head that is not on the matlab description files. Maybe there is some explanation for the absence of that translation and I don't know it. If not, we need to update the matlab files.

**Comment by mikearagao** [comment]
@ruipimentelfigueiredo is taking care of this here: 4cb336409b9e57ab652f8d8451458902889d378d

**Comment by plinioMoreno** [comment]
We'll see the translation that you talk about tomorrow, I guess it is 
the neck pitch (look up/down) but I'm almost sure that it is there.

On 2/5/2015 8:30 PM, Miguel Aragão wrote:
>
> @plinioMoreno <https://github.com/plinioMoreno> we were looking at the 
> translations and it looks like the real robot has a small one on the 
> head that is not on the matlab description files. Maybe there is some 
> explanation for the absence of that translation and I don't know it. 
> If not, we need to update the matlab files.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vislab-tecnico-lisboa/vizzy-description/issues/5#issuecomment-73120756>.
>

-- 
___________________

Plinio Moreno López
http://www.isr.ist.utl.pt/~plinio
plinio@isr.tecnico.ulisboa.pt
___________________

**Comment by mikearagao** [comment]
@plinioMoreno it's one that has translations over two different axis, but sure we'll see it tomorrow.

**Comment by ruipimentelfigueiredo** [comment]
@mikearagao @plinioMoreno Done 8)

**Comment by mikearagao** [comment]
Waiting for @plinioMoreno to fix the DH on the matlab description files. @ruipimentelfigueiredo can you take care of doing it again? After that I can align the meshes with the new origins!

**Comment by ruipimentelfigueiredo** [comment]
@mikearagao sure, let me know when the matlab files are updated

**Comment by mikearagao** [comment]
@ruipimentelfigueiredo ready and merged with master.

**Comment by mikearagao** [comment]
Any news on this issue @ruipimentelfigueiredo?

@aba92 is trying to work with Vizzy's simulator and right now with all the changes we're performing there is no stable version to work with... We should organize this so that next week we can have something tested :smiley:

**Comment by ruipimentelfigueiredo** [comment]
@mikearagao I am working on it right now. I will let you know as soon as I finish it :)

**Comment by ruipimentelfigueiredo** [comment]
done with this

**Comment by ruipimentelfigueiredo** [comment]
@mikearagao please check if possible that what I did is correct :D

**Comment by mikearagao** [comment]
Everything seems fine!
