### ISSUE TITLE
Change the names of joints and links to more meaningful ones

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy-description#8]
Try to find more descriptive names for the robot structures.

**Comment by ruipimentelfigueiredo** [comment]
@mikearagao @plinioMoreno I was looking at pr2 urdfs and it seems they use _link and _joint suffixes to distinguish between links and joints, respectively. They also use l_ and r_ to distinguish between left and right arm links and joints. So I guess we could do something similar

**Comment by ruipimentelfigueiredo** [comment]
done
